# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculate.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x63\x61lculate.proto\x12\x05proto\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\xdf\x01\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x32\n\x0bserver_type\x18\x02 \x01(\x0e\x32\x1d.proto.AddResponse.ServerType\x12.\n\tserver_id\x18\x03 \x01(\x0b\x32\x1b.proto.AddResponse.ServerId\x1a\x16\n\x08ServerId\x12\n\n\x02id\x18\x01 \x01(\t\"D\n\nServerType\x12\x0b\n\x07INVALID\x10\x00\x12\n\n\x06GOLANG\x10\x01\x12\n\n\x06PYTHON\x10\x02\x12\x08\n\x04JAVA\x10\x03\x12\x07\n\x03\x43PP\x10\x04\x32\x39\n\tCalculate\x12,\n\x03\x41\x64\x64\x12\x11.proto.AddRequest\x1a\x12.proto.AddResponseb\x06proto3')
)



_ADDRESPONSE_SERVERTYPE = _descriptor.EnumDescriptor(
  name='ServerType',
  full_name='proto.AddResponse.ServerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOLANG', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PYTHON', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JAVA', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CPP', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=218,
  serialized_end=286,
)
_sym_db.RegisterEnumDescriptor(_ADDRESPONSE_SERVERTYPE)


_ADDREQUEST = _descriptor.Descriptor(
  name='AddRequest',
  full_name='proto.AddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='proto.AddRequest.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='proto.AddRequest.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=60,
)


_ADDRESPONSE_SERVERID = _descriptor.Descriptor(
  name='ServerId',
  full_name='proto.AddResponse.ServerId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.AddResponse.ServerId.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=216,
)

_ADDRESPONSE = _descriptor.Descriptor(
  name='AddResponse',
  full_name='proto.AddResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='proto.AddResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server_type', full_name='proto.AddResponse.server_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server_id', full_name='proto.AddResponse.server_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ADDRESPONSE_SERVERID, ],
  enum_types=[
    _ADDRESPONSE_SERVERTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=286,
)

_ADDRESPONSE_SERVERID.containing_type = _ADDRESPONSE
_ADDRESPONSE.fields_by_name['server_type'].enum_type = _ADDRESPONSE_SERVERTYPE
_ADDRESPONSE.fields_by_name['server_id'].message_type = _ADDRESPONSE_SERVERID
_ADDRESPONSE_SERVERTYPE.containing_type = _ADDRESPONSE
DESCRIPTOR.message_types_by_name['AddRequest'] = _ADDREQUEST
DESCRIPTOR.message_types_by_name['AddResponse'] = _ADDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddRequest = _reflection.GeneratedProtocolMessageType('AddRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDREQUEST,
  __module__ = 'calculate_pb2'
  # @@protoc_insertion_point(class_scope:proto.AddRequest)
  ))
_sym_db.RegisterMessage(AddRequest)

AddResponse = _reflection.GeneratedProtocolMessageType('AddResponse', (_message.Message,), dict(

  ServerId = _reflection.GeneratedProtocolMessageType('ServerId', (_message.Message,), dict(
    DESCRIPTOR = _ADDRESPONSE_SERVERID,
    __module__ = 'calculate_pb2'
    # @@protoc_insertion_point(class_scope:proto.AddResponse.ServerId)
    ))
  ,
  DESCRIPTOR = _ADDRESPONSE,
  __module__ = 'calculate_pb2'
  # @@protoc_insertion_point(class_scope:proto.AddResponse)
  ))
_sym_db.RegisterMessage(AddResponse)
_sym_db.RegisterMessage(AddResponse.ServerId)



_CALCULATE = _descriptor.ServiceDescriptor(
  name='Calculate',
  full_name='proto.Calculate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=288,
  serialized_end=345,
  methods=[
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='proto.Calculate.Add',
    index=0,
    containing_service=None,
    input_type=_ADDREQUEST,
    output_type=_ADDRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATE)

DESCRIPTOR.services_by_name['Calculate'] = _CALCULATE

# @@protoc_insertion_point(module_scope)
